---
driver:
  name: vcenter
  vcenter_username: 'administrator@vsphere.local'
  vcenter_password: 'Good4bye!'
  vcenter_host: '172.16.20.2'
  vcenter_disable_ssl_verify: true

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec


platforms:
  - name: ubuntu-1604
    transport:
      username: "admini"
      password: admini
    driver_config:
      targethost: 172.16.20.43
      template: ubuntu16-tmpl
      datacenter: "Datacenter"

  - name: centos-7
    transport:
      username: "root"
      password: admini
    driver_config:
      targethost: 172.16.20.43
      template: centos7-tmpl
      datacenter: "Datacenter"

suites:
  - name: default
    run_list:
      - recipe[vmware-pipeline-example::default]
